### ISSUE TITLE
Env rollouts during imagination in dflex

### ISSUE THREAD

**Issue by Jogima-cyber** [imgeorgiev/PWM#1]
Hello,

Thank you for sharing your work. I have a question regarding the implementation of the actor loss computation. It appears that you run the simulator in parallel with the learned dynamics model to filter out "bad" trajectories when using the dflex simulator. Is my understanding correct?

**Comment by imgeorgiev** [comment]
Yes, the simulator is running in parallel with the learned dynamics model. However, don't think there is any filtering of bad trajectories. All of them are used for both world model learning and policy learning.

**Comment by Jogima-cyber** [comment]
Thank you for your answer. By "filtering bad trajectories," I meant stopping the imagined rollouts early in case of an early termination. Is this what you are implementing?

**Comment by imgeorgiev** [comment]
Ah yes, we do that indeed. When running the single task experiments in dflex, we get early termination flags from the simulation at which point we terminate the imagined rollout and start again from a (randomized) starting state. We do this for fair comparison with baselines such as PPO and SHAC.

**Comment by Jogima-cyber** [comment]
Thank you very much for your answer!
